# Generated by Django 5.0.6 on 2024-05-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatedvideo',
            name='file',
            field=models.FileField(upload_to='video_stream/'),
        ),
    ]
